version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: scriberr-proxy
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
